apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
  namespace: nginx
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: avi004/notes-app-k8s:latest
        ports:
        - containerPort: 8000